return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      preset = "modern",
      delay = 300,
      spec = {
        { "<leader>", group = "Press Space, then..." },
        { "<leader>e", desc = "Open File Sidebar" },
        { "<leader>d", desc = "Go To Definition" },
        { "<leader>r", desc = "Find All References" },
        { "<leader>a", desc = "Show Code Actions" },
        { "<leader>b", desc = "Toggle Git Blame" },
        { "<leader>j", desc = "Jump To Visible Text" },
        { "<leader>;", desc = "Pick Breadcrumb" },
        { "<leader>x", desc = "Close Current File" },
        { "<leader><leader>", desc = "Open Command Palette" },
        { "<leader>f", group = "Find / Search" },
        { "<leader>ff", desc = "Find Files" },
        { "<leader>fs", desc = "Search Text In Files" },
        { "<leader>fb", desc = "Find Open Files" },
        { "<leader>fo", desc = "Find Recent Files" },
        { "<leader>fk", desc = "Find Shortcuts" },
        { "<leader>fh", desc = "Find Help" },
        { "<leader>g", group = "Git / Format" },
        { "<leader>gf", desc = "Format Current File" },
        { "<leader>gp", desc = "Preview Git Change" },
        { "<leader>gv", desc = "Open Git Diff View" },
        { "<leader>gc", desc = "Close Git Diff View" },
        { "<leader>m", group = "Markdown / Preview" },
        { "<leader>mp", desc = "Toggle Markdown Preview" },
        { "<leader>q", group = "Sessions" },
        { "<leader>qs", desc = "Restore Session For This Folder" },
        { "<leader>ql", desc = "Restore Last Session" },
        { "<leader>qd", desc = "Stop Saving Session" },
        { "<leader>t", group = "Terminal" },
        { "<leader>tt", desc = "Toggle Terminal" },
        { "<leader>tn", desc = "Open New Terminal" },
        { "<leader>to", desc = "Pick Terminal" },
      },
    },
  },
}
